[package]
name = "cbuildrt"
version = "0.1.0"
authors = ["The Managarm Project <info@managarm.org>"]
edition = "2018"

[dependencies]
clap = "2.33"
libc = "0.2"
nix = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
