name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build cbuildrt
        runs-on: ubuntu-20.04
        steps:
          - name: Install prerequisites
            run: |
                rustup target add x86_64-unknown-linux-musl
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build using Cargo
            run: |
                cargo build --release --target x86_64-unknown-linux-musl
          - name: Publish artifact
            uses: actions/upload-artifact@v2
            with:
                name: cbuildrt-linux-x86_64
                path: target/x86_64-unknown-linux-musl/release/cbuildrt

    deploy:
        name: Publish release
        runs-on: ubuntu-20.04
        if: "startsWith(github.ref, 'refs/tags/v')"
        needs: build
        steps:
          - name: Fetch artifact
            uses: actions/download-artifact@v2
            with:
                name: cbuildrt-linux-x86_64
                path: linux-x86_64
          - name: Prepare assets
            run: |
                tar -cf cbuildrt-linux-x86_64-static.tar -C linux-x86_64 cbuildrt
          - name: Do release
            uses: softprops/action-gh-release@v1
            with:
                files: |
                    cbuildrt-linux-x86_64-static.tar
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
